SELECT * 
FROM USER 
WHERE AGE>60;

SELECT S.STATION_NAME, TS.ARR_TIME, TS.DEP_TIME, TS.PLATFORM
FROM TRAIN_STOP TS
JOIN STATION S ON TS.STATION_ID = S.STATION_ID
WHERE TS.TRAIN_ID = 12733
ORDER BY TS.ARR_TIME;

INSERT INTO TRAIN_STOP 
  (TRAIN_ID, STATION_ID, ARR_TIME, DEP_TIME, PLATFORM)
VALUES
  (17299, 21, '15:00:00', '15:10:00', 2);

SELECT 
  S.STATION_NAME,
  TS.ARR_TIME,
  TS.DEP_TIME,
  TS.PLATFORM
FROM TRAIN_STOP TS
JOIN STATION S ON TS.STATION_ID = S.STATION_ID
WHERE TS.TRAIN_ID = 17299
ORDER BY TS.ARR_TIME;

  SELECT 
    T.TICKET_ID,
    T.USER_ID,
    T.FARE,
    COALESCE(SUM(P.AMOUNT), 0) AS PAID
  FROM TICKET T
  LEFT JOIN PAYMENT P ON T.TICKET_ID = P.TICKET_ID
  WHERE T.TRAVEL_DATE BETWEEN '2025-07-01' AND '2025-07-31'
  GROUP BY T.TICKET_ID, T.USER_ID, T.FARE;
  
SELECT
  TR.TRAIN_NAME,
  TS.STATUS_NAME,
  COUNT(*) AS NUM_TICKETS
FROM TICKET T
JOIN TRAIN TR ON T.TRAIN_ID = TR.TRAIN_ID
JOIN TICKET_STATUS TS ON T.STATUS_ID = TS.STATUS_ID
WHERE T.TRAVEL_DATE = '2025-07-07'
GROUP BY TR.TRAIN_NAME, TS.STATUS_NAME
ORDER BY TR.TRAIN_NAME, TS.STATUS_NAME;

SELECT 
  U.USERNAME,
  TR.TRAIN_NAME,
  T.CLASS,
  T.TRAVEL_DATE,
  TS.STATUS_NAME
FROM TICKET T
JOIN USER U ON T.USER_ID = U.USER_ID
JOIN TRAIN TR ON T.TRAIN_ID = TR.TRAIN_ID
JOIN TICKET_STATUS TS ON T.STATUS_ID = TS.STATUS_ID
ORDER BY T.TRAVEL_DATE, U.USERNAME;
